[package]
name = "servermon"
version = "1.0.2"
authors = ["pi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.10"
toml = "0.5.5"
serde = "1.0.102"
serde_derive = "1.0.102"
